# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Posts and Tutorials"
  url = "#posts"
  weight = 4

[[main]]
  name = "Research By Topic"
  url = "#projects"
  weight = 2

[[main]]
  name = "Latest Research"
  url = "#featured"
  weight = 3

[[main]]
  name = "About Me"
  url = "#people"
  weight = 1
  
#[[main]]
#  name = "Meet the Team"
#  url = "#people"
#  weight = 5

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 6

#Link to a PDF of your resume/CV from the menu.
#to enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
    name = "CV"
    url = "files/cv_VanAlsten.pdf"
    weight = 70
